version: "3"
volumes:
  postgres_data:

services:
  db:
    # restart: always
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/data/postgres
      - ./docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
